name: uniflutterprot01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  flutter_local_notifications: ^12.0.2
  flutter_chat_ui: ^1.0.5
  flutter_chat_types: ^3.0.5
  agora_rtc_engine: ^5.1.0
  uuid: ^3.0.4
  connectivity_plus: ^2.3.0
  speech_to_text: ^6.6.0
  message_builder: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/WelcomeHomePG.png
    - assets/login_pgimg.png
    - assets/AluminiIcon.png
    - assets/CollegeIcon.png
    - assets/NetworkIcon.png
    - assets/SchoolIcon.png
    - assets/ConsultantsIcon.png
    - assets/userdataimage.png
    - assets/profileAvatar.webp
    - assets/Faqtop_nav_l.png
    - assets/Faqtop_nav_R.png
    - assets/findpgetopnav.png
    - assets/a.png
    - assets/b.png
    - assets/c.png
    - assets/d.png
    - assets/e.png
    - assets/f.png
    - assets/g.png
    - assets/h.png
    - assets/mit.jpeg
    - assets/icl.jpg
    - assets/hu.jpg
    - assets/uoc.jpeg
    - assets/su.jpeg
    - assets/eth.jpg
    - assets/nus.jpg
    - assets/ucl.jpg
    - assets/ciot.jpeg
    - assets/A&Qmainpage.png


